[package]
name = "ruizukun-dev/api-dump"
description = "A simple and reasonable module for working with the API dump from inside Roblox."
version = "1.1.1"
license = "MIT"
authors = ["Micah Reid <dekkonot@rocketmail.com>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

exclude = ["*"]
include = ["src", "src/*", "src/init.meta.json", 
"default.project.json", "wally.toml"]

[dependencies]